### ISSUE TITLE
What does DIVD stand for?

### ISSUE THREAD

**Issue by ketumbra** [DIVD-NL/web-csirt#751]
I can't see this anywhere on the website. I think it needs to be in the About section somewhere at least.

**Comment by Lennaert89** [comment]
Addressed by changes to:
https://www.divd.nl/who-we-are/

> Five years ago, a few enthusiastic hackers founded the Dutch Institute of Vulnerability Disclosure (DIVD) to make the digital world safer.

**Comment by JstRelax** [comment]
@ketumbra does that answer your question?

**Comment by ketumbra** [comment]
Yes, thanks.

**Comment by JstRelax** [comment]
Closed the issue
