### ISSUE TITLE
DMARC policy is obstructing the functionality of BIMI

### ISSUE THREAD

**Issue by freddieleeman** [DIVD-NL/web-csirt#765]
BIMI necessitates that the DMARC subdomain policy is set to something other than 'none'.

Validator: https://www.uriports.com/tools?method=bimi&domain=divd.nl

RFC: https://www.ietf.org/archive/id/draft-brand-indicators-for-message-identification-05.html#section-7.1

> If the DMARC [[RFC7489](https://www.ietf.org/archive/id/draft-brand-indicators-for-message-identification-05.html#RFC7489)] record for the Author Domain or Author Organizational Domain includes a subdomain policy, and that subdomain policy is sp=none then BIMI processing MUST NOT be performed for this message

Current DMARC policy:
`v=DMARC1; p=reject; pct=100; sp=none; rua=mailto:c411195b@inbox.ondmarc.com; ruf=mailto:c411195b@inbox.ondmarc.com; adkim=s; aspf=s; fo=1; rf=afrf; ri=3600`

**Comment by MrSeccubus** [comment]
Doorgezet naar IT services via Zammad (https://helpdesk.divd.network/#ticket/zoom/477)
Ik kom hier op terug. Bdankt voor het melden.

**Comment by freddieleeman** [comment]
You could have checked the validator referenced in the original comment to confirm that the issue is still unresolved.

https://www.uriports.com/tools?method=bimi&domain=divd.nl

**Comment by MrSeccubus** [comment]
Used the validator,. It says it looks great. Closing this issue.
Again thatnk @freddieleeman for reporting. Sorry it took so long.
